CREATE TABLE MAIN_LOG (
   START_DATE DATETIME,
   IP VARCHAR(20) NOT NULL,
   HTTP_REQ_TYPE VARCHAR(30),
   REQ_STATUS SMALLINT,
   DESCRIPTION TEXT
);
CREATE INDEX idx_ip ON MAIN_LOG (IP);

CREATE TABLE IP_ACTIVITY (
  IP VARCHAR(20) NOT NULL,
  START_DATE DATETIME,
  DURATION VARCHAR(20),
  REQ_COUNT INT
);